"""
marketplace/pilot_runner.py
===========================
Runs a lightweight marketplace pilot with 7-10 seeded nodes by placing randomized
buy/sell orders and printing aggregate outcomes.

Usage:
  python -m marketplace.pilot_runner --nodes 8 --rounds 3
"""

from __future__ import annotations

import argparse
import random
from collections import defaultdict
from typing import Dict, List

import requests

BASE_URL = "http://localhost:8000"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run a 7-10 node marketplace pilot")
    parser.add_argument("--base-url", default=BASE_URL, help="Marketplace base URL")
    parser.add_argument("--nodes", type=int, default=8, help="Number of nodes to include (7-10 recommended)")
    parser.add_argument("--rounds", type=int, default=3, help="Trading rounds per node")
    parser.add_argument("--seed", type=int, default=42, help="Random seed for reproducibility")
    parser.add_argument("--timeout", type=float, default=10.0, help="HTTP timeout per request (seconds)")
    return parser.parse_args()


def fetch_nodes(base_url: str, timeout: float) -> List[dict]:
    response = requests.get(f"{base_url}/orders", timeout=timeout)
    if response.status_code != 200:
        raise RuntimeError(f"Cannot contact marketplace: {response.status_code} {response.text}")

    # Node discovery fallback: try to infer from wallets endpoint path if /orders is reachable.
    # In this codebase, API keys are generated by seed_nodes.py and stored in node_keys.json.
    try:
        import json
        with open("node_keys.json", "r", encoding="utf-8") as f:
            data = json.load(f)
    except FileNotFoundError as exc:
        raise RuntimeError(
            "node_keys.json not found. Run `python -m marketplace.seed_nodes` first."
        ) from exc

    nodes = []
    for node_id, info in data.items():
        nodes.append(
            {
                "id": node_id,
                "city": info.get("city"),
                "api_key": info.get("api_key"),
            }
        )

    return nodes


def place_order(base_url: str, node: dict, order_type: str, qty: float, price: float, timeout: float) -> Dict:
    headers = {"X-API-Key": node["api_key"]}
    payload = {
        "node_id": node["id"],
        "order_type": order_type,
        "quantity_kwh": qty,
        "price_per_kwh": price,
    }
    response = requests.post(f"{base_url}/orders", json=payload, headers=headers, timeout=timeout)
    if response.status_code not in (200, 201):
        return {"ok": False, "status": response.status_code, "error": response.text}
    return {"ok": True, "data": response.json()}


def run_pilot(base_url: str, nodes: List[dict], rounds: int, seed: int, timeout: float) -> None:
    rng = random.Random(seed)
    stats = defaultdict(int)

    for _ in range(rounds):
        for node in nodes:
            order_type = "buy" if rng.random() < 0.5 else "sell"
            qty = round(rng.uniform(0.5, 3.0), 3)
            # Keep within configured grid reference spread-like range.
            price = round(rng.uniform(4.5, 8.0), 2)

            result = place_order(base_url, node, order_type, qty, price, timeout)
            if not result["ok"]:
                stats["failed_orders"] += 1
                continue

            stats["orders_placed"] += 1
            matched = bool(result["data"].get("matched"))
            if matched:
                stats["matched_orders"] += 1
                stats["trades_generated"] += len(result["data"].get("trades", []))

    market_stats = requests.get(f"{base_url}/stats", timeout=timeout)
    market_stats.raise_for_status()
    snapshot = market_stats.json()

    print("=" * 64)
    print("Marketplace Pilot Summary")
    print("=" * 64)
    print(f"Nodes in pilot           : {len(nodes)}")
    print(f"Rounds per node          : {rounds}")
    print(f"Orders placed            : {stats['orders_placed']}")
    print(f"Order placement failures : {stats['failed_orders']}")
    print(f"Orders matched           : {stats['matched_orders']}")
    print(f"Trades generated         : {stats['trades_generated']}")
    print("-" * 64)
    print(f"Total trades in market   : {snapshot.get('total_trades')}")
    print(f"Total volume (kWh)       : {snapshot.get('total_volume_kwh')}")
    print(f"Total value (INR)        : {snapshot.get('total_value_inr')}")
    print(f"Average price (INR/kWh)  : {snapshot.get('average_price_per_kwh')}")
    print("=" * 64)


def main() -> None:
    args = parse_args()
    if args.nodes < 1:
        raise ValueError("--nodes must be >= 1")

    nodes = fetch_nodes(args.base_url, args.timeout)
    if len(nodes) < args.nodes:
        raise RuntimeError(
            f"Requested {args.nodes} nodes but only {len(nodes)} keys found. "
            "Run `python -m marketplace.seed_nodes`. "
            "If nodes already exist and keys are missing, reset marketplace DB then reseed."
        )

    selected = nodes[: args.nodes]
    run_pilot(args.base_url, selected, args.rounds, args.seed, args.timeout)


if __name__ == "__main__":
    main()
